load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "digest",
    srcs = ["digest.go"],
    importpath = "github.com/kyleconroy/aws-build-farm/internal/digest",
    visibility = ["//:__subpackages__"],
    deps = ["@com_github_bazelbuild_remote_apis//build/bazel/remote/execution/v2:execution"],
)

go_test(
    name = "digest_test",
    srcs = ["digest_test.go"],
    embed = [":digest"],
    deps = ["@com_github_bazelbuild_remote_apis//build/bazel/remote/execution/v2:execution"],
)
