load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "cas",
    srcs = [
        "cas.go",
        "memstore.go",
    ],
    importpath = "github.com/kyleconroy/aws-build-farm/internal/cas",
    visibility = ["//:__subpackages__"],
    deps = [
        "//internal/digest",
        "@com_github_aws_aws_sdk_go_v2//aws",
        "@com_github_aws_aws_sdk_go_v2_feature_s3_manager//:manager",
        "@com_github_aws_aws_sdk_go_v2_service_s3//:s3",
        "@com_github_aws_aws_sdk_go_v2_service_s3//types",
        "@com_github_aws_smithy_go//:smithy-go",
        "@com_github_bazelbuild_remote_apis//build/bazel/remote/execution/v2:execution",
        "@org_golang_google_protobuf//proto",
    ],
)
